#!/bin/bash
apt-get update

wget http://www.rfxn.com/downloads/maldetect-current.tar.gz
tar -xvf maldetect-current.tar.gz
cd maldetect-*
./install.sh
maldet -u



apt-get install clamav clamav-daemon clamav-freshclam -y
/etc/init.d/clamav-daemon start


wget https://raw.githubusercontent.com/arsanto/ubuntu-blog-install/master/conf.maldet -O /usr/local/maldetect/conf.maldet



maldet --include-regex ".*.php$" -a /www/wwwroot
